### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [SevenLines/pinterest-board-downloader#2]
I try to download a board and receive this error:
```

Traceback (most recent call last):
  File "/usr/local/bin/pinterest", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/src/__init__.py", line 151, in main
    boards = get_board_info(args.path)
  File "/usr/local/lib/python3.8/dist-packages/src/__init__.py", line 68, in get_board_info
    boards = initial_data['resources'] \
KeyError: 'resources'

```

**Comment by searchformyusername** [comment]
same error, **some fix that you know?**
```
(env) PS C:\Users\Dell\Desktop\pinterest_d> pinterest henjesuestrella/fashion-men-style/formal
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\pinterest_d\env\Scripts\pinterest-script.py", line 11, in <module>
    load_entry_point('pinterest-downloader==0.0.1', 'console_scripts', 'pinterest')()
  File "c:\users\dell\desktop\pinterest_d\env\lib\site-packages\src\__init__.py", line 151, in main
    boards = get_board_info(args.path)
  File "c:\users\dell\desktop\pinterest_d\env\lib\site-packages\src\__init__.py", line 68, in get_board_info
    boards = initial_data['resources'] \
KeyError: 'resources'
```

**Comment by BreadMakesYouFull** [comment]
Hey @SevenLines, I have a PR to fix this issue you might be interested in merging. :)
