### ISSUE TITLE
Installed ok but errors on run

### ISSUE THREAD

**Issue by Capitalmind** [SevenLines/pinterest-board-downloader#9]
Traceback (most recent call last):
  File "/home/$USER/.local/bin/pinterest", line 8, in <module>
    sys.exit(main())
  File "/home/$USER/.local/lib/python3.8/site-packages/src/__init__.py", line 300, in main
    boards = [get_board_info(path) for path in paths]
  File "/home/$USER/.local/lib/python3.8/site-packages/src/__init__.py", line 300, in <listcomp>
    boards = [get_board_info(path) for path in paths]
  File "/home/$USER/.local/lib/python3.8/site-packages/src/__init__.py", line 148, in get_board_info
    initial_data
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Mist-Hunter** [comment]
Same issue.

Got this during install if it helps:

Installing collected packages: urllib3, idna, chardet, requests, lxml, pinterest-downloader
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.2
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'urllib3'. No files were found to uninstall.
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Not uninstalling idna at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'idna'. No files were found to uninstall.
  Attempting uninstall: chardet
    Found existing installation: chardet 4.0.0
    Not uninstalling chardet at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'chardet'. No files were found to uninstall.
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'requests'. No files were found to uninstall.

**Comment by derekb123** [comment]
Having an error as well: 

`IndexError: list index out of range`
